version: '3.8'

services:
  # Frontend Development Server
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: workflow-admin-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "3000:3000"  # External browser access
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload in Docker
    networks:
      - workflow-admin
    
networks:
  workflow-admin:
    external: 
      name: workflow-admin_workflow-admin  # Use existing network from main compose